=== HerculesCRUE/GnossDeustoBackend/src/cvn/cvn/mappings/cvn/1.4.2_sp1/XSD/Subtypes.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2007 sp2 (http://www.altova.com) by RAFAEL GARCIA TAMARIT (FUNDACION ESPAÃ‘OLA DE CIENCIA Y TECNOLOGIA) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:spec="http://cv.normalizado.org/CVNSubtype" xmlns:cvn="http://cv.normalizado.org/cvn" targetNamespace="http://cv.normalizado.org/CVNSubtype" elementFormDefault="unqualified" attributeFormDefault="unqualified">
	<xs:annotation>
		<xs:documentation>
						Version: 1.0.0		
		</xs:documentation>
		<xs:documentation>
				Author:FECYT 
				http://www.fecyt.es
				http://cv.normalizado.org
		</xs:documentation>
	</xs:annotation>
	<xs:import namespace="http://cv.normalizado.org/cvn" schemaLocation="ISOUtilities.xsd"/>
	<xs:element name="CVNSubtype">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Subtype">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Item" maxOccurs="unbounded">
								<xs:complexType>
									<xs:complexContent>
										<xs:extension base="spec:ItemType">
											<xs:attribute name="code" use="required"/>
										</xs:extension>
									</xs:complexContent>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="version" use="required"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<!-- elementos principales del item-->
	<xs:complexType name="ItemType">
		<xs:sequence>
			<xs:element name="Name" type="spec:NameType"/>
			<xs:element name="CodeSubtype1" type="xs:string"/>
			<xs:element name="CodeSubtype2" type="xs:string" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<!-- tipos de datos-->
	<xs:complexType name="NameType">
		<xs:sequence>
			<xs:element name="NameDetail" maxOccurs="unbounded">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="Name" type="xs:string"/>
						<xs:element name="ShortName" type="xs:string" minOccurs="0"/>
					</xs:sequence>
					<xs:attribute name="lang" type="cvn:ISO_639" use="required"/>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== HerculesCRUE/GnossDeustoBackend/src/cvn/cvn/mappings/cvn/1.4.2_sp1/XML/Subtype_Spa.xml
<?xml version="1.0" encoding="UTF-8"?>
<CVNSubtype xmlns="http://cv.normalizado.org/CVNSubtype" xmlns:cvn="http://cv.normalizado.org/cvn" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://cv.normalizado.org/CVNSubtype Subtypes.xsd">
	<Subtype xmlns="" version="1.4.0">
		<Item code="001">
			<Name>
				<NameDetail lang="spa">
					<Name>Aportaciones más relevantes del CV docencia</Name>
				</NameDetail>
			</Name>
			<CodeSubtype1>002</CodeSubtype1>
		</Item>
		<Item code="003">
			<Name>
				<NameDetail lang="spa">
					<Name>Ayudas y Becas Obtenidas</Name>
				</NameDetail>
			</Name>
			<CodeSubtype1>007</CodeSubtype1>
		</Item>
		<Item code="054">
			<Name>
				<NameDetail lang="spa">
					<Name>Protocolos y Otros materiales de atención de salud</Name>
				</NameDetail>
			</Name>
			<CodeSubtype1>009</CodeSubtype1>
		</Item>
		<Item code="167">
			<Name>
				<NameDetail lang="spa">
					<Name>Publicación en Revista</Name>
				</NameDetail>
			</Name>
			<CodeSubtype1>009</CodeSubtype1>
			<CodeSubtype2>125</CodeSubtype2>
		</Item>
		<Item code="119">
			<Name>
				<NameDetail lang="spa">
					<Name>Libro y/o Manual</Name>
				</NameDetail>
			</Name>
			<CodeSubtype1>009</CodeSubtype1>
			<CodeSubtype2>126</CodeSubtype2>
		</Item>
		<Item code="168">
			<Name>
				<NameDetail lang="spa">
					<Name>Publicación Períodica</Name>
				</NameDetail>
			</Name>
			<CodeSubtype1>009</CodeSubtype1>
			<CodeSubtype2>127</CodeSubtype2>
		</Item>
		<Item code="111">
			<Name>
				<NameDetail lang="spa">
					<Name>Documento o Informe científico-técnico</Name>
				</NameDetail>
			</Name>
			<CodeSubtype1>009</CodeSubtype1>
			<CodeSubtype2>128</CodeSubtype2>
		</Item>
		<Item code="114">
			<Name>
				<NameDetail lang="spa">
					<Name>Grabaciones Sonoras</Name>
				</NameDetail>
			</Name>
			<CodeSubtype1>009</CodeSubtype1>
			<CodeSubtype2>131</CodeSubtype2>
		</Item>
		<Item code="144">
			<Name>
				<NameDetail lang="spa">
					<Name>Peliculas y Videograbaciones</Name>
				</NameDetail>
			</Name>
			<CodeSubtype1>009</CodeSubtype1>
			<CodeSubtype2>132</CodeSubtype2>
		</Item>
		<Item code="165">
			<Name>
				<NameDetail lang="spa">
					<Name>Software</Name>
				</NameDetail>
			</Name>
			<CodeSubtype1>009</CodeSubtype1>
			<CodeSubtype2>133</CodeSubtype2>
		</Item>
		<Item code="006">
			<Name>
				<NameDetail lang="spa">
					<Name>Catálogo de obra artística</Name>
				</NameDetail>
			</Name>
			<CodeSubtype1>012</CodeSubtype1>
		</Item>
		<Item code="007">
			<Name>
				<NameDetail lang="spa">
					<Name>Comité Científico asesores, Sociedades Científica</Name>
				</NameDetail>
			</Name>
			<CodeSubtype1>014</CodeSubtype1>
		</Item>
		<Item code="008">
			<Name>
				<NameDetail lang="spa">
					<Name>Congreso</Name>
				</NameDetail>
			</Name>
			<CodeSubtype1>015</CodeSubtype1>
		</Item>
		<Item code="086">
			<Name>
				<NameDetail lang="spa">
					<Name>Comunicación</Name>
				</NameDetail>
			</Name>
			<CodeSubtype1>015</CodeSubtype1>
			<CodeSubtype2>155</CodeSubtype2>
		</Item>
		<Item code="091">
			<Name>
				<NameDetail lang="spa">
					<Name>Conferencia y demás aportaciones no publicadas</Name>
				</NameDetail>
			</Name>
			<CodeSubtype1>015</CodeSubtype1>
			<CodeSubtype2>164</CodeSubtype2>
		</Item>
		<Item code="156">
			<Name>
				<NameDetail lang="spa">
					<Name>Poster</Name>
				</NameDetail>
			</Name>
			<CodeSubtype1>015</CodeSubtype1>
			<CodeSubtype2>165</CodeSubtype2>
		</Item>
		<Item code="101">
			<Name>
				<NameDetail lang="spa">
					<Name>Demostración de Producto o Servicio</Name>
				</NameDetail>
			</Name>
			<CodeSubtype1>015</CodeSubtype1>
			<CodeSubtype2>167</CodeSubtype2>
		</Item>
		<Item code="152">
			<Name>
				<NameDetail lang="spa">
					<Name>Ponencia</Name>
				</NameDetail>
			</Name>
			<CodeSubtype1>015</CodeSubtype1>
			<CodeSubtype2>178</CodeSubtype2>
		</Item>
		<Item code="134">
			<Name>
				<NameDetail lang="spa">
					<Name>Participación en Mesa Redonda</Name>
				</NameDetail>
			</Name>
			<CodeSubtype1>015</CodeSubtype1>
			<CodeSubtype2>213</CodeSubtype2>
		</Item>
		<Item code="186">
			<Name>
				<NameDetail lang="spa">
					<Name>Ponencia en sesión plenaria</Name>
				</NameDetail>
			</Name>
			<CodeSubtype1>015</CodeSubtype1>
			<CodeSubtype2>243</CodeSubtype2>
		</Item>
		<Item code="187">
			<Name>
				<NameDetail lang="spa">
					<Name>Ponencia en sesión no plenaria</Name>
				</NameDetail>
			</Name>
			<CodeSubtype1>015</CodeSubtype1>
			<CodeSubtype2>244</CodeSubtype2>
		</Item>
		<Item code="010">
			<Name>
				<NameDetail lang="spa">
					<Name>Convenios de colaboración</Name>
				</NameDetail>
			</Name>
			<CodeSubtype1>016</CodeSubtype1>
		</Item>
		<Item code="011">
			<Name>
				<NameDetail lang="spa">
					<Name>Curso</Name>
				</NameDetail>
			</Name>
			<CodeSubtype1>018</CodeSubtype1>
		</Item>
		<Item code="138">
			<Name>
				<NameDetail lang="spa">
					<Name>Participación en Mesa Redonda</Name>
				</NameDetail>
			</Name>
			<CodeSubtype1>018</CodeSubtype1>
			<CodeSubtype2>158</CodeSubtype2>
		</Item>
		<Item code="150">
			<Name>
				<NameDetail lang="spa">
					<Name>Ponencia</Name>
				</NameDetail>
			</Name>
			<CodeSubtype1>018</CodeSubtype1>
			<CodeSubtype2>192</CodeSubtype2>
		</Item>
		<Item code="085">
			<Name>
				<NameDetail lang="spa">
					<Name>Comunicación</Name>
				</NameDetail>
			</Name>
			<CodeSubtype1>018</CodeSubtype1>
			<CodeSubtype2>210</CodeSubtype2>
		</Item>
		<Item code="088">
			<Name>
				<NameDetail lang="spa">
					<Name>Conferencia y demás aportaciones no publicadas</Name>
				</NameDetail>
			</Name>
			<CodeSubtype1>018</CodeSubtype1>
			<CodeSubtype2>219</CodeSubtype2>
		</Item>
		<Item code="160">
			<Name>
				<NameDetail lang="spa">
					<Name>Poster</Name>
				</NameDetail>
			</Name>
			<CodeSubtype1>018</CodeSubtype1>
			<CodeSubtype2>220</CodeSubtype2>
		</Item>
		<Item code="102">
			<Name>
				<NameDetail lang="spa">
					<Name>Demostración de Producto o Servicio</Name>
				</NameDetail>
			</Name>
			<CodeSubtype1>018</CodeSubtype1>
			<CodeSubtype2>222</CodeSubtype2>
		</Item>
		<Item code="188">
			<Name>
				<NameDetail lang="spa">
					<Name>Ponencia en sesión plenaria</Name>
				</NameDetail>
			</Name>
			<CodeSubtype1>018</CodeSubtype1>
			<CodeSubtype2>245</CodeSubtype2>
		</Item>
		<Item code="189">
			<Name>
				<NameDetail lang="spa">
					<Name>Ponencia en sesión no plenaria</Name>
				</NameDetail>
			</Name>
			<CodeSubtype1>018</CodeSubtype1>
			<CodeSubtype2>246</CodeSubtype2>
		</Item>
		<Item code="012">
			<Name>
				<NameDetail lang="spa">
					<Name>Cursos, Programas o Seminarios</Name>
				</NameDetail>
			</Name>
			<CodeSubtype1>019</CodeSubtype1>
		</Item>
		<Item code="146">
			<Name>
				<NameDetail lang="spa">
					<Name>Perfecionamiento Docente</Name>
				</NameDetail>
			</Name>
			<CodeSubtype1>019</CodeSubtype1>
			<CodeSubtype2>053</CodeSubtype2>
		</Item>
		<Item code="096">
			<Name>
				<NameDetail lang="spa">
					<Name>Cursos de Especializacion</Name>
				</NameDetail>
			</Name>
			<CodeSubtype1>019</CodeSubtype1>
			<CodeSubtype2>057</CodeSubtype2>
		</Item>
		<Item code="133">
			<Name>
				<NameDetail lang="spa">
					<Name>Para la mejora de la atención de Salud para Profesionales Sanitarios</Name>
				</NameDetail>
			</Name>
			<CodeSubtype1>019</CodeSubtype1>
			<CodeSubtype2>058</CodeSubtype2>
		</Item>
		<Item code="163">
			<Name>
				<NameDetail lang="spa">
					<Name>Programa de Formación Sanitaria Especializada</Name>
				</NameDetail>
			</Name>
			<CodeSubtype1>019</CodeSubtype1>
			<CodeSubtype2>059</CodeSubtype2>
		</Item>
		<Item code="162">
			<Name>
				<NameDetail lang="spa">
					<Name>Programa de Formación de I+D  y/o Postformación Sanitaria</Name>
				</NameDetail>
			</Name>
			<CodeSubtype1>019</CodeSubtype1>
			<CodeSubtype2>060</CodeSubtype2>
		</Item>
		<Item code="014">
			<Name>
				<NameDetail lang="spa">
					<Name>Docencia Internacional</Name>
				</NameDetail>
			</Name>
			<CodeSubtype1>027</CodeSubtype1>
		</Item>
		<Item code="015">
			<Name>
				<NameDetail lang="spa">
					<Name>Docencia No Oficial</Name>
				</NameDetail>
			</Name>
			<CodeSubtype1>028</CodeSubtype1>
		</Item>
		<Item code="016">
			<Name>
				<NameDetail lang="spa">
					<Name>Docencia Oficial</Name>
				</NameDetail>
			</Name>
			<CodeSubtype1>029</CodeSubtype1>
		</Item>
		<Item code="020">
			<Name>
				<NameDetail lang="spa">
					<Name>Artículo científico</Name>
				</NameDetail>
			</Name>
			<CodeSubtype1>035</CodeSubtype1>
		</Item>
		<Item code="021">
			<Name>
				<NameDetail lang="spa">
					<Name>Experiencia de Atención de salud en otros Paises Extranjeros</Name>
				</NameDetail>
			</Name>
			<CodeSubtype1>036</CodeSubtype1>
		</Item>
		<Item code="022">
			<Name>
				<NameDetail lang="spa">
					<Name>Experiencia en cooperación sanitaria en paises en desarrollo</Name>
				</NameDetail>
			</Name>
			<CodeSubtype1>037</CodeSubtype1>
		</Item>
		<Item code="023">
			<Name>
				<NameDetail lang="spa">
					<Name>Experiencia Sanitaria en Cooperación de Atención de Salud en países en desarrollo</Name>
				</NameDetail>
			</Name>
			<CodeSubtype1>038</CodeSubtype1>
		</Item>
		<Item code="024">
			<Name>
				<NameDetail lang="spa">
					<Name>Experiencia Sanitaria en Instituciones de la UE</Name>
				</NameDetail>
			</Name>
			<CodeSubtype1>039</CodeSubtype1>
		</Item>
		<Item code="025">
			<Name>
				<NameDetail lang="spa">
					<Name>Experiencia Sanitaria en Instituciones en las OMS</Name>
				</NameDetail>
			</Name>
			<CodeSubtype1>040</CodeSubtype1>
		</Item>
		<Item code="026">
			<Name>
				<NameDetail lang="spa">
					<Name>Experiencia Sanitaria en Otros Organismos Internacionales</Name>
				</NameDetail>
			</Name>
			<CodeSubtype1>041</CodeSubtype1>
		</Item>
		<Item code="027">
			<Name>
				<NameDetail lang="spa">
